# Generated by Django 5.2.4 on 2025-07-17 04:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Updated at"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Created at"
                    ),
                ),
                (
                    "review_id",
                    models.CharField(
                        db_index=True, help_text="ID review on platform", max_length=100
                    ),
                ),
                ("author", models.CharField(blank=True, max_length=255)),
                ("rating", models.PositiveSmallIntegerField()),
                ("title", models.CharField(blank=True, max_length=500)),
                ("content", models.TextField()),
                ("version", models.CharField(blank=True, max_length=50)),
                (
                    "platform_updated_at",
                    models.DateTimeField(help_text="Date and time of the last update"),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, help_text="Metadata"),
                ),
                (
                    "app_platform_data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="app.appplatformdata",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["app_platform_data", "updated_at"],
                        name="review_revi_app_pla_5e3c32_idx",
                    ),
                    models.Index(
                        fields=["review_id"], name="review_revi_review__755fa0_idx"
                    ),
                ],
                "unique_together": {("app_platform_data", "review_id")},
            },
        ),
    ]
