# Generated by Django 5.2.4 on 2025-08-01 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review_analysis", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysisresult",
            name="analysis_source",
            field=models.CharField(
                choices=[
                    ("local", "Local Analysis"),
                    ("gpt", "GPT Analysis"),
                    ("manual", "Manual Override"),
                    ("none", "No Analysis (All Steps Disabled)"),
                ],
                default="local",
                help_text="Source of the analysis",
                max_length=20,
            ),
        ),
    ]
