# Generated by Django 5.2.4 on 2025-07-12 01:06

from django.db import migrations

def create_user_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.get_or_create(name='free')
    Group.objects.get_or_create(name='premium')

class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_user_groups),
    ]
