# Generated by Django 5.2.4 on 2025-07-16 04:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="App",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Updated at"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Created at"
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("competitors", models.ManyToManyField(blank=True, to="app.app")),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AppPlatformData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("appstore", "App Store"),
                            ("play_market", "Play Market"),
                            ("product_hunt", "Product Hunt"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "platform_app_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("bundle_id", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "developer_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("name", models.CharField(max_length=200)),
                ("current_version", models.CharField(max_length=50)),
                ("current_version_release_date", models.DateTimeField()),
                ("icon_url", models.URLField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(max_length=10)),
                ("rating_average", models.DecimalField(decimal_places=2, max_digits=3)),
                ("rating_count", models.PositiveIntegerField()),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "extra_metadata",
                    models.JSONField(
                        blank=True,
                        help_text="Description, screenshots, genres, languages, devices, etc.",
                        null=True,
                    ),
                ),
                (
                    "app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="platform_data",
                        to="app.app",
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("app", "platform"),
                    ("platform", "bundle_id"),
                    ("platform", "platform_app_id"),
                },
            },
        ),
    ]
