# Generated by Django 5.2.4 on 2025-08-01 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="app",
            name="metadata",
            field=models.JSONField(
                blank=True,
                help_text="Additional metadata for the app (featured, tags, etc.)",
                null=True,
            ),
        ),
    ]
